# Generated by Django 4.1 on 2023-07-31 19:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="transaction_id",
        ),
    ]
